//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DraftCleanerRunner.DraftCleanerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DraftCleanerService.IDraftCleanerServiceWcf")]
    public interface IDraftCleanerServiceWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDraftCleanerServiceWcf/RemoveOldDrafts", ReplyAction="http://tempuri.org/IDraftCleanerServiceWcf/RemoveOldDraftsResponse")]
        void RemoveOldDrafts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDraftCleanerServiceWcf/RemoveOldDrafts", ReplyAction="http://tempuri.org/IDraftCleanerServiceWcf/RemoveOldDraftsResponse")]
        System.Threading.Tasks.Task RemoveOldDraftsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDraftCleanerServiceWcfChannel : DraftCleanerRunner.DraftCleanerService.IDraftCleanerServiceWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DraftCleanerServiceWcfClient : System.ServiceModel.ClientBase<DraftCleanerRunner.DraftCleanerService.IDraftCleanerServiceWcf>, DraftCleanerRunner.DraftCleanerService.IDraftCleanerServiceWcf {
        
        public DraftCleanerServiceWcfClient() {
        }
        
        public DraftCleanerServiceWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DraftCleanerServiceWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DraftCleanerServiceWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DraftCleanerServiceWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void RemoveOldDrafts() {
            base.Channel.RemoveOldDrafts();
        }
        
        public System.Threading.Tasks.Task RemoveOldDraftsAsync() {
            return base.Channel.RemoveOldDraftsAsync();
        }
    }
}
